package cr.ac.una.Inge2.proyecto.mhuw.domain;
// Generated 08-sep-2018 18:49:14 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer pkIdCliente;
     private Usuario usuario;
     private String cedula;
     private String nombre;
     private String apellidos;
     private String telefono;
     private String direccion;
     private String nacionalidad;
     private Integer ultimoUsuario;
     private Date fechaModificacion;
     private Set<Controlservicios> controlservicioses = new HashSet<Controlservicios>(0);
     private Set<Factura> facturas = new HashSet<Factura>(0);

    public Cliente() {
    }

	
    public Cliente(Usuario usuario, String cedula, String nombre, String apellidos, String telefono, String nacionalidad) {
        this.usuario = usuario;
        this.cedula = cedula;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.telefono = telefono;
        this.nacionalidad = nacionalidad;
    }
    public Cliente(Usuario usuario, String cedula, String nombre, String apellidos, String telefono, String direccion, String nacionalidad, Integer ultimoUsuario, Date fechaModificacion, Set<Controlservicios> controlservicioses, Set<Factura> facturas) {
       this.usuario = usuario;
       this.cedula = cedula;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.telefono = telefono;
       this.direccion = direccion;
       this.nacionalidad = nacionalidad;
       this.ultimoUsuario = ultimoUsuario;
       this.fechaModificacion = fechaModificacion;
       this.controlservicioses = controlservicioses;
       this.facturas = facturas;
    }
   
    public Integer getPkIdCliente() {
        return this.pkIdCliente;
    }
    
    public void setPkIdCliente(Integer pkIdCliente) {
        this.pkIdCliente = pkIdCliente;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }
    public Integer getUltimoUsuario() {
        return this.ultimoUsuario;
    }
    
    public void setUltimoUsuario(Integer ultimoUsuario) {
        this.ultimoUsuario = ultimoUsuario;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Set<Controlservicios> getControlservicioses() {
        return this.controlservicioses;
    }
    
    public void setControlservicioses(Set<Controlservicios> controlservicioses) {
        this.controlservicioses = controlservicioses;
    }
    public Set<Factura> getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set<Factura> facturas) {
        this.facturas = facturas;
    }




}


