package cr.ac.una.Inge2.proyecto.mhuw.domain;
// Generated 08-sep-2018 18:49:14 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Controlservicios generated by hbm2java
 */
public class Controlservicios  implements java.io.Serializable {


     private Integer pkIdControlServicio;
     private Cliente cliente;
     private Servicios servicios;
     private Date fechaCreacion;
     private Integer ultimoUsuario;
     private Date fechaModificacion;

    public Controlservicios() {
    }

	
    public Controlservicios(Cliente cliente, Servicios servicios, Date fechaCreacion) {
        this.cliente = cliente;
        this.servicios = servicios;
        this.fechaCreacion = fechaCreacion;
    }
    public Controlservicios(Cliente cliente, Servicios servicios, Date fechaCreacion, Integer ultimoUsuario, Date fechaModificacion) {
       this.cliente = cliente;
       this.servicios = servicios;
       this.fechaCreacion = fechaCreacion;
       this.ultimoUsuario = ultimoUsuario;
       this.fechaModificacion = fechaModificacion;
    }
   
    public Integer getPkIdControlServicio() {
        return this.pkIdControlServicio;
    }
    
    public void setPkIdControlServicio(Integer pkIdControlServicio) {
        this.pkIdControlServicio = pkIdControlServicio;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Servicios getServicios() {
        return this.servicios;
    }
    
    public void setServicios(Servicios servicios) {
        this.servicios = servicios;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Integer getUltimoUsuario() {
        return this.ultimoUsuario;
    }
    
    public void setUltimoUsuario(Integer ultimoUsuario) {
        this.ultimoUsuario = ultimoUsuario;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


