package cr.ac.una.Inge2.proyecto.mhuw.domain;
// Generated 03-oct-2018 19:51:19 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Direccion generated by hbm2java
 */
public class Direccion  implements java.io.Serializable {


     private Integer idDireccion;
     private String provincia;
     private String canton;
     private String distrito;
     private String tipo;
     private String otrasSenas;
     private Set<Estudiante> estudiantes = new HashSet<Estudiante>(0);

    public Direccion() {
    }

	
    public Direccion(String provincia, String canton, String distrito, String tipo) {
        this.provincia = provincia;
        this.canton = canton;
        this.distrito = distrito;
        this.tipo = tipo;
    }
    public Direccion(String provincia, String canton, String distrito, String tipo, String otrasSenas, Set<Estudiante> estudiantes) {
       this.provincia = provincia;
       this.canton = canton;
       this.distrito = distrito;
       this.tipo = tipo;
       this.otrasSenas = otrasSenas;
       this.estudiantes = estudiantes;
    }
   
    public Integer getIdDireccion() {
        return this.idDireccion;
    }
    
    public void setIdDireccion(Integer idDireccion) {
        this.idDireccion = idDireccion;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public String getCanton() {
        return this.canton;
    }
    
    public void setCanton(String canton) {
        this.canton = canton;
    }
    public String getDistrito() {
        return this.distrito;
    }
    
    public void setDistrito(String distrito) {
        this.distrito = distrito;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getOtrasSenas() {
        return this.otrasSenas;
    }
    
    public void setOtrasSenas(String otrasSenas) {
        this.otrasSenas = otrasSenas;
    }
    public Set<Estudiante> getEstudiantes() {
        return this.estudiantes;
    }
    
    public void setEstudiantes(Set<Estudiante> estudiantes) {
        this.estudiantes = estudiantes;
    }




}


