package cr.ac.una.Inge2.proyecto.mhuw.domain;
// Generated 08-sep-2018 18:49:14 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private Integer pkIdFactura;
     private Cliente cliente;
     private Servicios servicios;
     private Date fechaCreacion;
     private String descripcion;

    public Factura() {
    }

    public Factura(Cliente cliente, Servicios servicios, Date fechaCreacion, String descripcion) {
       this.cliente = cliente;
       this.servicios = servicios;
       this.fechaCreacion = fechaCreacion;
       this.descripcion = descripcion;
    }
   
    public Integer getPkIdFactura() {
        return this.pkIdFactura;
    }
    
    public void setPkIdFactura(Integer pkIdFactura) {
        this.pkIdFactura = pkIdFactura;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Servicios getServicios() {
        return this.servicios;
    }
    
    public void setServicios(Servicios servicios) {
        this.servicios = servicios;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


