package cr.ac.una.Inge2.proyecto.mhuw.domain;
// Generated 03-oct-2018 19:51:19 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Grupo generated by hbm2java
 */
public class Grupo  implements java.io.Serializable {


     private Integer idGrupo;
     private Funcionario funcionario;
     private int nrc;
     private String nombre;
     private int numero;
     private Integer ultimoUsuario;
     private Date fechaModificacion;

    public Grupo() {
    }

	
    public Grupo(Funcionario funcionario, int nrc, String nombre, int numero) {
        this.funcionario = funcionario;
        this.nrc = nrc;
        this.nombre = nombre;
        this.numero = numero;
    }
    public Grupo(Funcionario funcionario, int nrc, String nombre, int numero, Integer ultimoUsuario, Date fechaModificacion) {
       this.funcionario = funcionario;
       this.nrc = nrc;
       this.nombre = nombre;
       this.numero = numero;
       this.ultimoUsuario = ultimoUsuario;
       this.fechaModificacion = fechaModificacion;
    }
   
    public Integer getIdGrupo() {
        return this.idGrupo;
    }
    
    public void setIdGrupo(Integer idGrupo) {
        this.idGrupo = idGrupo;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public int getNrc() {
        return this.nrc;
    }
    
    public void setNrc(int nrc) {
        this.nrc = nrc;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public Integer getUltimoUsuario() {
        return this.ultimoUsuario;
    }
    
    public void setUltimoUsuario(Integer ultimoUsuario) {
        this.ultimoUsuario = ultimoUsuario;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


