package cr.ac.una.Inge2.proyecto.mhuw.domain;
// Generated 03-oct-2018 19:51:19 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Salud generated by hbm2java
 */
public class Salud  implements java.io.Serializable {


     private Integer idSalud;
     private String enfermedades;
     private String alergias;
     private String lesiones;
     private String necesidadEspecial;
     private String tipoSangre;
     private Integer ultimoUsuario;
     private Date fechaModificacion;
     private Set<Estudiante> estudiantes = new HashSet<Estudiante>(0);

    public Salud() {
    }

    public Salud(String enfermedades, String alergias, String lesiones, String necesidadEspecial, String tipoSangre, Integer ultimoUsuario, Date fechaModificacion, Set<Estudiante> estudiantes) {
       this.enfermedades = enfermedades;
       this.alergias = alergias;
       this.lesiones = lesiones;
       this.necesidadEspecial = necesidadEspecial;
       this.tipoSangre = tipoSangre;
       this.ultimoUsuario = ultimoUsuario;
       this.fechaModificacion = fechaModificacion;
       this.estudiantes = estudiantes;
    }
   
    public Integer getIdSalud() {
        return this.idSalud;
    }
    
    public void setIdSalud(Integer idSalud) {
        this.idSalud = idSalud;
    }
    public String getEnfermedades() {
        return this.enfermedades;
    }
    
    public void setEnfermedades(String enfermedades) {
        this.enfermedades = enfermedades;
    }
    public String getAlergias() {
        return this.alergias;
    }
    
    public void setAlergias(String alergias) {
        this.alergias = alergias;
    }
    public String getLesiones() {
        return this.lesiones;
    }
    
    public void setLesiones(String lesiones) {
        this.lesiones = lesiones;
    }
    public String getNecesidadEspecial() {
        return this.necesidadEspecial;
    }
    
    public void setNecesidadEspecial(String necesidadEspecial) {
        this.necesidadEspecial = necesidadEspecial;
    }
    public String getTipoSangre() {
        return this.tipoSangre;
    }
    
    public void setTipoSangre(String tipoSangre) {
        this.tipoSangre = tipoSangre;
    }
    public Integer getUltimoUsuario() {
        return this.ultimoUsuario;
    }
    
    public void setUltimoUsuario(Integer ultimoUsuario) {
        this.ultimoUsuario = ultimoUsuario;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Set<Estudiante> getEstudiantes() {
        return this.estudiantes;
    }
    
    public void setEstudiantes(Set<Estudiante> estudiantes) {
        this.estudiantes = estudiantes;
    }




}


