package cr.ac.una.Inge2.proyecto.mhuw.domain;
// Generated 03-oct-2018 19:51:19 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Telefonos generated by hbm2java
 */
public class Telefonos  implements java.io.Serializable {


     private Integer idTelefonos;
     private String habitacion;
     private String celular;
     private String trabajo;
     private Set<Funcionario> funcionarios = new HashSet<Funcionario>(0);
     private Set<Estudiante> estudiantes = new HashSet<Estudiante>(0);

    public Telefonos() {
    }

    public Telefonos(String habitacion, String celular, String trabajo, Set<Funcionario> funcionarios, Set<Estudiante> estudiantes) {
       this.habitacion = habitacion;
       this.celular = celular;
       this.trabajo = trabajo;
       this.funcionarios = funcionarios;
       this.estudiantes = estudiantes;
    }
   
    public Integer getIdTelefonos() {
        return this.idTelefonos;
    }
    
    public void setIdTelefonos(Integer idTelefonos) {
        this.idTelefonos = idTelefonos;
    }
    public String getHabitacion() {
        return this.habitacion;
    }
    
    public void setHabitacion(String habitacion) {
        this.habitacion = habitacion;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public String getTrabajo() {
        return this.trabajo;
    }
    
    public void setTrabajo(String trabajo) {
        this.trabajo = trabajo;
    }
    public Set<Funcionario> getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Set<Funcionario> funcionarios) {
        this.funcionarios = funcionarios;
    }
    public Set<Estudiante> getEstudiantes() {
        return this.estudiantes;
    }
    
    public void setEstudiantes(Set<Estudiante> estudiantes) {
        this.estudiantes = estudiantes;
    }




}


