package cr.ac.una.Inge2.proyecto.mhuw.domain;
// Generated 03-oct-2018 19:51:19 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer pkIdUsuario;
     private String usuario;
     private String ukEmail;
     private String passwordSha512;
     private String passwordBcrypt;
     private int tipo;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private Integer ultimoUsuario;
     private int estado;
     private String codigoConfirmacion;
     private Set<Estudiante> estudiantes = new HashSet<Estudiante>(0);
     private Set<Controlarticulos> controlarticuloses = new HashSet<Controlarticulos>(0);
     private Set<Funcionario> funcionarios = new HashSet<Funcionario>(0);
     private Set<Comentarios> comentarioses = new HashSet<Comentarios>(0);
     private Set<Controlchats> controlchatsesForFkIdUsuarioOrigen = new HashSet<Controlchats>(0);
     private Set<Controlchats> controlchatsesForFkIdUsuarioDestino = new HashSet<Controlchats>(0);

    public Usuario() {
    }

	
    public Usuario(String usuario, String ukEmail, String passwordSha512, String passwordBcrypt, int tipo, Date fechaCreacion, int estado) {
        this.usuario = usuario;
        this.ukEmail = ukEmail;
        this.passwordSha512 = passwordSha512;
        this.passwordBcrypt = passwordBcrypt;
        this.tipo = tipo;
        this.fechaCreacion = fechaCreacion;
        this.estado = estado;
    }
    public Usuario(String usuario, String ukEmail, String passwordSha512, String passwordBcrypt, int tipo, Date fechaCreacion, Date fechaModificacion, Integer ultimoUsuario, int estado, String codigoConfirmacion, Set<Estudiante> estudiantes, Set<Controlarticulos> controlarticuloses, Set<Funcionario> funcionarios, Set<Comentarios> comentarioses, Set<Controlchats> controlchatsesForFkIdUsuarioOrigen, Set<Controlchats> controlchatsesForFkIdUsuarioDestino) {
       this.usuario = usuario;
       this.ukEmail = ukEmail;
       this.passwordSha512 = passwordSha512;
       this.passwordBcrypt = passwordBcrypt;
       this.tipo = tipo;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.ultimoUsuario = ultimoUsuario;
       this.estado = estado;
       this.codigoConfirmacion = codigoConfirmacion;
       this.estudiantes = estudiantes;
       this.controlarticuloses = controlarticuloses;
       this.funcionarios = funcionarios;
       this.comentarioses = comentarioses;
       this.controlchatsesForFkIdUsuarioOrigen = controlchatsesForFkIdUsuarioOrigen;
       this.controlchatsesForFkIdUsuarioDestino = controlchatsesForFkIdUsuarioDestino;
    }
   
    public Integer getPkIdUsuario() {
        return this.pkIdUsuario;
    }
    
    public void setPkIdUsuario(Integer pkIdUsuario) {
        this.pkIdUsuario = pkIdUsuario;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getUkEmail() {
        return this.ukEmail;
    }
    
    public void setUkEmail(String ukEmail) {
        this.ukEmail = ukEmail;
    }
    public String getPasswordSha512() {
        return this.passwordSha512;
    }
    
    public void setPasswordSha512(String passwordSha512) {
        this.passwordSha512 = passwordSha512;
    }
    public String getPasswordBcrypt() {
        return this.passwordBcrypt;
    }
    
    public void setPasswordBcrypt(String passwordBcrypt) {
        this.passwordBcrypt = passwordBcrypt;
    }
    public int getTipo() {
        return this.tipo;
    }
    
    public void setTipo(int tipo) {
        this.tipo = tipo;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Integer getUltimoUsuario() {
        return this.ultimoUsuario;
    }
    
    public void setUltimoUsuario(Integer ultimoUsuario) {
        this.ultimoUsuario = ultimoUsuario;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }
    public String getCodigoConfirmacion() {
        return this.codigoConfirmacion;
    }
    
    public void setCodigoConfirmacion(String codigoConfirmacion) {
        this.codigoConfirmacion = codigoConfirmacion;
    }
    public Set<Estudiante> getEstudiantes() {
        return this.estudiantes;
    }
    
    public void setEstudiantes(Set<Estudiante> estudiantes) {
        this.estudiantes = estudiantes;
    }
    public Set<Controlarticulos> getControlarticuloses() {
        return this.controlarticuloses;
    }
    
    public void setControlarticuloses(Set<Controlarticulos> controlarticuloses) {
        this.controlarticuloses = controlarticuloses;
    }
    public Set<Funcionario> getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Set<Funcionario> funcionarios) {
        this.funcionarios = funcionarios;
    }
    public Set<Comentarios> getComentarioses() {
        return this.comentarioses;
    }
    
    public void setComentarioses(Set<Comentarios> comentarioses) {
        this.comentarioses = comentarioses;
    }
    public Set<Controlchats> getControlchatsesForFkIdUsuarioOrigen() {
        return this.controlchatsesForFkIdUsuarioOrigen;
    }
    
    public void setControlchatsesForFkIdUsuarioOrigen(Set<Controlchats> controlchatsesForFkIdUsuarioOrigen) {
        this.controlchatsesForFkIdUsuarioOrigen = controlchatsesForFkIdUsuarioOrigen;
    }
    public Set<Controlchats> getControlchatsesForFkIdUsuarioDestino() {
        return this.controlchatsesForFkIdUsuarioDestino;
    }
    
    public void setControlchatsesForFkIdUsuarioDestino(Set<Controlchats> controlchatsesForFkIdUsuarioDestino) {
        this.controlchatsesForFkIdUsuarioDestino = controlchatsesForFkIdUsuarioDestino;
    }




}


